# Generated by Django 4.1.5 on 2023-05-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0015_alter_expert_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImg', models.ImageField(null=True, upload_to='%Y/%m/%d/')),
            ],
        ),
    ]
