# Generated by Django 4.1.6 on 2023-06-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0016_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
