# Generated by Django 4.1.5 on 2023-06-22 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0019_tanalyze_patientlist_forumquestion_forumanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.forumquestion'),
        ),
    ]
