# Generated by Django 4.1.5 on 2023-06-28 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pybo', '0019_tanalyze_patientlist_forumquestion_forumanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_img', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_img_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
