# Generated by Django 4.1.5 on 2023-06-27 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_alter_forumanswer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.question'),
        ),
    ]
