# Generated by Django 4.1.5 on 2023-07-04 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0020_profile_img'),
        ('pybo', '0021_alter_forumanswer_question'),
    ]

    operations = [
    ]
