# Generated by Django 4.1.5 on 2023-07-04 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0022_merge_20230704_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pybo.forumquestion'),
        ),
    ]
