# Generated by Django 4.1.6 on 2023-07-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0024_animal_ranking_category_pet2_animal_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal_ranking',
            name='voter_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
